
#label for organizational purposes
[transdiy]
#path to pushshift comments file
comments = funnymemes_comments.zst
#path to pushshift submissions file
posts = funnymemes_submissions.zst


# Add as many other sections as you want.
[funnymemescontinued]
comments = funnymemes_comments.zst
posts = funnymemes_submissions.zst
