
#subreddit name
[funny]
#path to pushshift comments file
comments = funny_comments.zst
#path to pushshift submissions file
posts = funny_submissions.zst

#Add other subs if you like
[funnymemes]
comments = funnymemes_comments.zst
posts = funnymemes_submissions.zst